#!/bin/zsh

zstyle :completion::complete:-command-:: tag-order local-directories -

#export PROMPT='%{$fg[red]%}'
#export PS1='\[\033[01;32m\]# $(__hostname)\[\033[01;34m\] \w \[\033[31m\]$(__git_ps1 "(%s)")\n\[\033[01;32m\]> \[\033[00m\]'

autoload -U colors && colors
PS1="%{$fg_bold[green]%}# %m %{$fg_bold[blue]%}%~ %{$reset_color%}
%{$fg_bold[green]%}> %{$reset_color%}"
