#!/bin/bash
CUR_DIR=`pwd`

#
# Undo stuff before sourcing anything
#

for a in l ll la; do
  if alias -p | grep $a &>/dev/null; then
    unalias $a &>/dev/null
  fi
done

# Platform specific (first because some stuff in here relies on it)
#

case `uname` in
  Darwin) source $HOME/program_store/dotfiles/rc/profile_Darwin ;;
  Linux)  source $HOME/program_store/dotfiles/rc/profile_Linux ;;
esac

SEDI_OPTION="-r"
if [ -z "$IS_DARWIN"]; then
  SEDI_OPTION="-E"
fi

#
# Paths etc
#

# Mac gets crappy hostname sometimes.
__hostname() {
  hostname -s | sed $SEDI_OPTION 's/dhcp-(.*)$/mac/'
}
export PS1='\[\033[01;32m\]# $(__hostname)\[\033[01;34m\] \w \[\033[31m\]$(__git_ps1 "(%s)")\n\[\033[01;32m\]> \[\033[00m\]'

export EDITOR="vim"
export SVN_LOG_EDITOR="$EDITOR"
export PATH="/usr/bin:$PATH"

#
# General
#

fn()      { find . -name "$@"; }
c()       { cd -P "$@"; }
ll()      { l -l "$@"; }
la()      { l -A "$@"; }
lla()     { l -lA "$@"; }
v()       { vim -p "$@"; }
e()       { vim -p $(echo $@ | sed 's/:/ +/'); }
wg()      { wget --no-check-certificate -O- "$@"; }
grr()     { grep -rn --color --exclude='.svn' "$@"; }
agg()     { ack --color "$@" | more -R; }
s()       { screen -DR "$@"; }
prepend() { sed "s|^|$1" "$@"; }
sx()      { ssh -Y "$@"; }

vl() {
  file=`echo "$1" | cut -d: -f1`
  line=`echo "$1" | cut -d: -f2`
  v "$file" +"$line"
}

#
# Git
#

source $HOME/program_store/dotfiles/ben_profile/git_completion

complete -o default -o nospace -F _git_branch changed
complete -o default -o nospace -F _git_branch cherry-pick
complete -o default -o nospace -F _git_branch gb
complete -o default -o nospace -F _git_branch gcb
complete -o default -o nospace -F _git_branch ghide
complete -o default -o nospace -F _git_checkout gch
complete -o default -o nospace -F _git_checkout gchr
complete -o default -o nospace -F _git_diff gd
complete -o default -o nospace -F _git_diff gdt
complete -o default -o nospace -F _git_diff gdns
complete -o default -o nospace -F _git_diff gds
complete -o default -o nospace -F _git_merge_base gmb
complete -o default -o nospace -F _git_log gl
complete -o default -o nospace -F _git_rebase gr

g()    { git "$@"; }
ga()   { git add "$@"; }
gb()   { git branch "$@" | grep -v '^  __' | grep -v ' master$'; }
gbD()  {
  read -p 'Are you sure? [y/N] ' -n1 READ;
  if [ "$READ" == 'y' ]; then git branch -D "$@"; fi
}
gc()   { git commit "$@"; }
gcaa() { gc -a --amend; }
gch()  { git checkout "$@"; }
gcp()  { git cherry-pick "$@"; }
gd()   { git diff "$@"; }
gdns() { git diff --name-status "$@"; }
gds()  { git diff --stat "$@"; }
gdt()  { git difftool "$@"; }
gg()   { git grep "$@"; }
gl()   { git log "$@"; }
gls()  { git ls-files "$@"; }
gm()   { git merge "$@"; }
gmb()  { git merge-base "$@"; }
gp()   { git pull "$@"; }
gr()   { git rebase "$@"; }
gs()   { git status "$@"; }

unmerged() {
  git status -s | grep '^[AUD][AUD] ' | cut -f2 -d' '
}

gC() {
  gc -m `gcb` "$@"
}

gcb() {
  git branch | grep '^*' | cut -f2- -d' '
}

gbase() {
  gmb `gcb` origin/master
}

grev() {
  gl | grep Cr-Commit-Position | head -n1 | sed $SEDI_OPTION 's/.*\{#(.*+)\}.*/\1/g'
}

gtry() {
  g cl try -r `grev`
}

ghide() {
  if [ -z "$1" ]; then
    echo "ERROR: no branch(es) supplied"
    return
  fi
  for branch in "$@"; do
    gb "$branch" -m "__`date +%F`__$branch"
  done
}

gclean() {
  current_date=`date +%F | tr -d -`
  for branch in `git branch | grep -E '__[0-9-]+__'`; do
    branch_date=`echo "$branch" | grep -Eo '__[0-9-]+__' | tr -d _-`
    if [ $branch_date -lt $(( $current_date - 100 )) ]; then
      read -N 1 -p "Delete $branch [N/y] "
      echo
      if [ "$REPLY" = y ]; then
        git branch -D "$branch"
        echo
      fi
    fi
  done

  read -N 1 -p "Run \"git gc\" [N/y] "
  echo
  if [ "$REPLY" = y ]; then
    git gc
  fi
}

changed() {
  base="$1"
  if [ -z "$base" ]; then
    base=`gbase`
  fi
  gdns "$base" | cut -f2
}

gchr() {
  oldBranch=`gcb`
  branch="$1"
  if [ -z "$branch" ]; then
    echo "ERROR: no branch supplied"
    return
  fi
  gch "$branch"
  gr "$oldBranch"
}

crt() {
  target="$1"
  filter="$2"
  shift 2
  if [ -z "$target" ]; then
    echo "Usage: $0 target [filter]"
    return
  fi
  if [ -n "$filter" ]; then
    filter="--gtest_filter=$filter"
  fi
  "$target" "$filter" "$@"
}

gf() {
  gls "*/$1"
}

gsquash() {
  g reset `gbase`
  ga chrome
  gC
}

export CRDIR="$HOME/chromium"
cdc() {
  c "${CRDIR}${1}"
}

crbr() {
  if [ -z "$1" ]; then
    echo "Usage: $0 TESTNAME args..."
    return 1
  fi

  local testname="$1"
  shift

  crclang "$testname" && "b/$testname" "$@"
}

greplace() {
  from="$1"
  to="$2"

  shift 2

  for f in `gg -l "$@" "$from"`; do
    echo "Replacing in $f"
    sedi $SED_I_SUFFIX "s%$from%$to%g" "$f"
  done
}

gclu() {
  g cl upload `gbase` "$@"
}

gfindconfigpath() {
  startdir="`pwd`"
  path='.git/config'
  while [ ! -f "${startdir}/${path}" ]; do
    path="../${path}"
    cd ..
    if [ "`pwd`" == "/" ]; then
      echo .
      return 1
    fi
  done
  echo "$path"
  cd "$startdir"
}

gh() {
  grep '\[branch "' "`gfindconfigpath`" \
    | sed 's/^.*"\(.*\)".*$/\1/' \
    | grep -v '^__'
}

gfc() {
  issue="$1"
  if [ -z "$issue" ]; then
    echo "Usage: gfc <issue>"
    return 1
  fi
  grep "rietveldissue = $issue" "`gfindconfigpath`" -B10 \
    | grep '^\[branch ' \
    | tail -n1 \
    | sed $SEDI_OPTION 's/\[branch "(.*)"\].*/\1/'
}

jsonp() {
  echo "$1" | python -m json.tool
}

#
# Chromium
#

po() {
  old_dir=`pwd`
  if [ -d "$1" ]; then
    cd "$1"
  elif [ -f "$1" ]; then
    cd `dirname "$1"`
  else
    echo "Couldn't find file or directory $1"
    return 1
  fi

  print_owners() {
    if [ -f OWNERS ]; then
      echo "=== `pwd`"
      cat OWNERS
      echo
    fi
  }

  while [ `pwd` != "$old_dir" -a `pwd` != / ]; do
    print_owners
    cd ..
  done
  print_owners

  unset print_owners
  cd "$old_dir"
}

crb() {
  version="$1"
  if [ "$version" == '-r' ]; then
    dir='gnr'
  elif [ "$version" == '-d' ]; then
    dir='gnd'
  else
    dir="$version"
  fi
  shift 1
  targets="$@"
  if [ -z "$targets" ]; then
    targets='all'
  fi
  #${GOMA_DIR}/goma_ctl.py ensure_start
  ninja -C "out/${dir}" "$targets" -j500
}

gnr() {
  crb -r "$@"
}

gnd() {
  crb -d "$@"
}

gsync() {
  gclient sync -n
}

#
# HANA
#

puha() {
  branch="$1"
  if [ "$branch" == '-h' ]; then
    echo "git push ssh://i333043@hdbgerrit.wdf.sap.corp:29418/hana HEAD:refs/for/sql_opt_dev"
    return 1
  elif [ -z "$branch" ]; then
    branch="sql_opt_dev"
  fi
  git push ssh://i333043@hdbgerrit.wdf.sap.corp:29418/hana HEAD:refs/for/$branch
}

# ghf - [G]rep [H]istory [F]or top ten commands and execute one
# usage:
#  Most frequent command in recent history
#   ghf
#  Most frequent instances of {command} in all history
#   ghf {command}
#  Execute {command-number} after a call to ghf
#   !! {command-number}
function latest-history { history | tail -n 50 ; }
function grepped-history { history | grep "$1" ; }
function chop-first-column { awk '{for (i=2; i<NF; i++) printf $i " "; print $NF}' ; }
function add-line-numbers { awk '{print NR " " $0}' ; }
function top-ten { sort | uniq -c | sort -r | head -n 10 ; }
function unique-history { chop-first-column | top-ten | chop-first-column | add-line-numbers ; }
function ghf {
  if [ $# -eq 0 ]; then latest-history | unique-history; fi
  if [ $# -eq 1 ]; then grepped-history "$1" | unique-history; fi
  if [ $# -eq 2 ]; then
    `grepped-history "$1" | unique-history | grep ^$2 | chop-first-column`;
  fi
}

#
# K8S
#

kc()   { echo "Current KUBECONFIG: "; echo $KUBECONFIG; }
k()    { kubectl "$@"; }
kg()   { kubectl get "$@"; kc; }
kgp()  { kg po --sort-by=.status.startTime; }
kget()   { kubectl get "$@"; kc; }
khaas()   { export KUBECONFIG=/Users/i333043/program_store/landscape/generated/kubeconfig-i333043-haas.yaml; kc;}
korc()   { export KUBECONFIG=/Users/i333043/program_store/landscape/generated/kubeconfig-i333043-orc.yaml; kc;}

khaas2()   { export KUBECONFIG=/Users/i333043/program_store/landscape/generated/kubeconfig-i333043-2-haas.yaml; kc;}
korc2()   { export KUBECONFIG=/Users/i333043/program_store/landscape/generated/kubeconfig-i333043-2-orc.yaml; kc;}

khaas9()   { export KUBECONFIG=/Users/i333043/program_store/landscape/generated/kubeconfig-i333043-9-haas.yaml; kc;}
korc9()   { export KUBECONFIG=/Users/i333043/program_store/landscape/generated/kubeconfig-i333043-9-orc.yaml; kc;}
